<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>Update</name>
   <tag></tag>
   <elementGuidId>1c8adaeb-4416-4b7e-8bd5-cb19b5bdc54a</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\r\n    \&quot;period_year\&quot; : \&quot;2020\&quot;,\r\n    \&quot;period_month\&quot;: \&quot;10\&quot;,\r\n    \&quot;work_hour\&quot; : [\r\n        {\r\n            \&quot;date\&quot; : 19,\r\n            \&quot;work_hour_id\&quot; : [2,3]\r\n        }, \r\n        {\r\n            \&quot;date\&quot; : 20,\r\n            \&quot;work_hour_id\&quot; : [1,2]\r\n        }\r\n    ]\r\n}&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Proxy-Authorization</name>
      <type>Main</type>
      <value>${SECRET_SERVICE}</value>
      <webElementGuid>e6eb4d36-1af5-44c6-a8cc-f05dd6a71569</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>8dc24a00-6515-4e3a-bebf-ceb3436975c6</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>Bearer ${alpha_token}</value>
      <webElementGuid>794b359e-25ea-438a-a028-adb11cc64106</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>10.0.1</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <path></path>
   <restRequestMethod>PUT</restRequestMethod>
   <restUrl>${alpha_gw_api_url}/employees/schedules/${employee_schedule_id}/shift/period/${shift_period_id}</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.alpha_gw_api_url</defaultValue>
      <description></description>
      <id>9b96d9d5-52c4-4247-82d8-6a715b4cde2b</id>
      <masked>false</masked>
      <name>alpha_gw_api_url</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.employee_schedule_id</defaultValue>
      <description></description>
      <id>19057c8f-eb4e-4fef-88bb-28c9034fe7b5</id>
      <masked>false</masked>
      <name>employee_schedule_id</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.shift_period_id</defaultValue>
      <description></description>
      <id>b8cf3313-cd3f-4dd1-96df-8ac6c9895524</id>
      <masked>false</masked>
      <name>shift_period_id</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.SECRET_SERVICE</defaultValue>
      <description></description>
      <id>7e3265b6-e553-4c6b-9a97-fc468cf6a7b9</id>
      <masked>false</masked>
      <name>SECRET_SERVICE</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.alpha_token</defaultValue>
      <description></description>
      <id>baa3cc78-bb88-4256-b9ee-53815b4bc747</id>
      <masked>false</masked>
      <name>alpha_token</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
