<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>Update</name>
   <tag></tag>
   <elementGuidId>d657c57b-882b-4fde-8e9b-b3584458905d</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\n    \&quot;firstname\&quot;: \&quot;Jane\&quot;,\n    \&quot;middlename\&quot;: \&quot;Mary\&quot;,\n    \&quot;lastname\&quot;: \&quot;Doe\&quot;,\n    \&quot;birthdate\&quot;: \&quot;1990-01-01\&quot;,\n    \&quot;gender\&quot;: \&quot;female\&quot;,\n    \&quot;email\&quot;: \&quot;jane@admin.com\&quot;,\n    \&quot;join_date\&quot;: \&quot;2020-07-23\&quot;,\n    \&quot;personal_email\&quot;: \&quot;janedoe@mailinator.com\&quot;,\n    \&quot;blood_type\&quot;: \&quot;a\&quot;,\n    \&quot;blood_type_rh\&quot;: \&quot;+\&quot;,\n    \&quot;marital_status\&quot;: \&quot;single\&quot;,\n    \&quot;phone\&quot;: \&quot;081808180818\&quot;,\n    \&quot;mobile_phone\&quot;: \&quot;081808180818\&quot;,\n    \&quot;address\&quot;: \&quot;Somewhere in Surabaya\&quot;,\n    \&quot;home_address\&quot;: \&quot;Somewhere in Surabaya\&quot;,\n    \&quot;id_type\&quot;: \&quot;passport\&quot;,\n    \&quot;id_number\&quot;: \&quot;X123456\&quot;,\n    \&quot;id_expiration\&quot;: \&quot;2020-12-31\&quot;,\n    \&quot;family_card_no\&quot;: \&quot;1234567890123456\&quot;,\n    \&quot;avatar_url\&quot;: \&quot;/images/temp/brie_larson.jpeg\&quot;,\n    \&quot;internal_id\&quot;: \&quot;2007951\&quot;,\n    \&quot;facebook\&quot;: \&quot;facebook ku\&quot;,\n    \&quot;twitter\&quot; : \&quot;twitter ku\&quot;,\n    \&quot;instagram\&quot; : \&quot;instagram ku\&quot;,\n    \&quot;linkedin\&quot; : \&quot;linkedin ku\&quot;\n}&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>0dc4372e-0499-409a-a765-60980cc85425</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>8aaed773-dd8f-4469-9747-d703e4d9fce3</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>10.0.1</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <path></path>
   <restRequestMethod>PUT</restRequestMethod>
   <restUrl>${alpha_gw_api_url}/employees/${alpha_header_user_id_value}</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.alpha_gw_api_url</defaultValue>
      <description></description>
      <id>e4669cab-5c3b-42eb-b63d-e85150d6cc89</id>
      <masked>false</masked>
      <name>alpha_gw_api_url</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.alpha_header_user_id_value</defaultValue>
      <description></description>
      <id>2f866d5b-4464-4fff-a389-c6692b84144a</id>
      <masked>false</masked>
      <name>alpha_header_user_id_value</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
