<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>Store</name>
   <tag></tag>
   <elementGuidId>44a28e51-8b23-4c2d-bb9c-2e5163c3940f</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\r\n    \&quot;company_setting_id\&quot; : 1,\r\n    \&quot;position_id\&quot; : 2,\r\n    \&quot;budgeted\&quot; : 1,\r\n    \&quot;device_id\&quot; : 2,\r\n    \&quot;device_received_id\&quot; : 3,\r\n    \&quot;total_request\&quot; : 3,\r\n    \&quot;date_needed\&quot; : \&quot;2023-08-01\&quot;,\r\n    \&quot;existing_employee_count\&quot; : 10,\r\n    \&quot;salary_min\&quot; : 1000000,\r\n    \&quot;salary_max\&quot; : 5000000,\r\n    \&quot;status_request\&quot; : {\r\n            \&quot;type\&quot; : \&quot;new\&quot;,\r\n            \&quot;employee_id\&quot; : null\r\n    },\r\n    \&quot;work_from\&quot; : {\r\n            \&quot;type\&quot; : \&quot;hybrid\&quot;,\r\n            \&quot;office_id\&quot; : 1\r\n    },\r\n    \&quot;summary\&quot; : \&quot;Lorem ipsum\&quot;,\r\n    \&quot;requirment\&quot; : \&quot;Dolor sit amet\&quot;,\r\n    \&quot;job_description\&quot; : \&quot;Do bi do bi do\&quot;,\r\n    \&quot;note\&quot; : \&quot;nothing\&quot;\r\n}&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>5a105dfe-a4d5-43b4-a327-9cd48a122d85</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>bf8d64a1-b6a7-42d0-80f4-dc715407d3b2</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Proxy-Authorization</name>
      <type>Main</type>
      <value>${SECRET_SERVICE}</value>
      <webElementGuid>90ac0c95-1ee5-4651-ad23-b5174daf881a</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>${alpha_header_user_id_key}</name>
      <type>Main</type>
      <value>${alpha_header_user_id_value}</value>
      <webElementGuid>eef99a8c-5df9-4ff6-9b44-a7a332624f4b</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>10.0.1</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <path></path>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>${alpha_gw_api_url}/employee-requests</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.alpha_gw_api_url</defaultValue>
      <description></description>
      <id>5d85843a-5f94-43b8-b4b1-7f921db70c34</id>
      <masked>false</masked>
      <name>alpha_gw_api_url</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.SECRET_SERVICE</defaultValue>
      <description></description>
      <id>8b8c82e7-d1f2-4f83-845b-9692058178a3</id>
      <masked>false</masked>
      <name>SECRET_SERVICE</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.alpha_header_user_id_key</defaultValue>
      <description></description>
      <id>7a30dbb8-0e4b-40fb-a3d7-0554458288f9</id>
      <masked>false</masked>
      <name>alpha_header_user_id_key</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.alpha_header_user_id_value</defaultValue>
      <description></description>
      <id>72aeedf4-998c-4be2-87c7-2064ba68351e</id>
      <masked>false</masked>
      <name>alpha_header_user_id_value</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
