<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>Update</name>
   <tag></tag>
   <elementGuidId>61f2638e-b6ff-46c4-b9a0-68221b8ddaff</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\r\n    \&quot;position_id\&quot; : 2,\r\n    \&quot;budgeted\&quot; : 1,\r\n    \&quot;device_id\&quot; : 2,\r\n    \&quot;device_received_id\&quot; : 3,\r\n    \&quot;total_request\&quot; : 3,\r\n    \&quot;date_needed\&quot; : \&quot;2023-08-01\&quot;,\r\n    \&quot;existing_employee_count\&quot; : 10,\r\n    \&quot;salary_min\&quot; : 1000000,\r\n    \&quot;salary_max\&quot; : 5000000,\r\n    \&quot;status_request\&quot; : {\r\n            \&quot;type\&quot; : \&quot;new\&quot;,\r\n            \&quot;employee_id\&quot; : null\r\n    },\r\n    \&quot;work_from\&quot; : {\r\n            \&quot;type\&quot; : \&quot;hybrid\&quot;,\r\n            \&quot;office_id\&quot; : 1\r\n    },\r\n    \&quot;summary\&quot; : \&quot;Lorem ipsum\&quot;,\r\n    \&quot;requirment\&quot; : \&quot;Dolor sit amet\&quot;,\r\n    \&quot;job_description\&quot; : \&quot;Do bi do bi do\&quot;,\r\n    \&quot;note\&quot; : \&quot;nothing\&quot;\r\n}&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>ed067154-f7b9-4d5b-96c0-5ed9f77b57a6</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>ac4853ee-ec53-4840-8924-243869781764</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Proxy-Authorization</name>
      <type>Main</type>
      <value>${SECRET_SERVICE}</value>
      <webElementGuid>6bbe5b5c-e70d-4d14-813a-f635c6f1554f</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>${alpha_header_user_id_key}</name>
      <type>Main</type>
      <value>${alpha_header_user_id_value}</value>
      <webElementGuid>e0ddc643-2ea6-4303-b510-b997d4ce659f</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>10.0.1</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <path></path>
   <restRequestMethod>PUT</restRequestMethod>
   <restUrl>${alpha_gw_api_url}/employee-requests/${employee_request_id}</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.alpha_gw_api_url</defaultValue>
      <description></description>
      <id>0fee541c-bf75-41ed-b0cd-738bc06cad70</id>
      <masked>false</masked>
      <name>alpha_gw_api_url</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.employee_request_id</defaultValue>
      <description></description>
      <id>4ffb4198-6f89-497e-83d5-a4f5702829ab</id>
      <masked>false</masked>
      <name>employee_request_id</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.SECRET_SERVICE</defaultValue>
      <description></description>
      <id>48be9d79-648f-4f7a-bebd-b2e2b8cdc23f</id>
      <masked>false</masked>
      <name>SECRET_SERVICE</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.alpha_header_user_id_key</defaultValue>
      <description></description>
      <id>ca7d9076-c491-4791-ad9e-4d71565fb58a</id>
      <masked>false</masked>
      <name>alpha_header_user_id_key</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.alpha_header_user_id_value</defaultValue>
      <description></description>
      <id>a186256c-7b7d-49a6-9489-12dbc9a32a86</id>
      <masked>false</masked>
      <name>alpha_header_user_id_value</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
