<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>Create</name>
   <tag></tag>
   <elementGuidId>63411634-b860-47c9-b53a-a9aec8534c60</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\r\n    \&quot;company_logo\&quot; : \&quot;\&quot;,\r\n    \&quot;company_icon\&quot; : \&quot;\&quot;,\r\n    \&quot;column_class\&quot; : \&quot;company1\&quot;,\r\n    \&quot;company_name\&quot; : \&quot;Haduw\&quot;,\r\n    \&quot;company_hrd_email\&quot; : \&quot;hrd@apple.com\&quot;,\r\n    \&quot;account_holder_email\&quot; : \&quot;hrd@apple.com\&quot;,\r\n    \&quot;company_tax_id\&quot; : \&quot;\&quot;,\r\n    \&quot;company_address_1\&quot; : \&quot;Surabaya\&quot;,\r\n    \&quot;company_address_2\&quot; : \&quot;\&quot;,\r\n    \&quot;company_country\&quot; : \&quot;Indonesia\&quot;,\r\n    \&quot;company_state\&quot; : \&quot;East Java\&quot;,\r\n    \&quot;company_city\&quot; : \&quot;Surabaya\&quot;,\r\n    \&quot;company_zip_code\&quot; : \&quot;61372\&quot;,\r\n    \&quot;company_default_locale\&quot; : \&quot;id-ID\&quot;,\r\n    \&quot;max_upload_filesize\&quot; : \&quot;2000\&quot;,\r\n    \&quot;status\&quot; : \&quot;0\&quot;,\r\n    \&quot;leave_setting_default_status\&quot; : \&quot;9\&quot;,\r\n    \&quot;leave_setting_annual_quota\&quot; : \&quot;ok\&quot;,\r\n    \&quot;expense_setting_default_status\&quot; : \&quot;9\&quot;,\r\n    \&quot;expense_setting_autocomplete\&quot; : \&quot;ok\&quot;,\r\n    \&quot;payroll_cutoff_date\&quot; : \&quot;24\&quot;,\r\n    \&quot;master_data\&quot; : [\&quot;departments\&quot;, \&quot;job_categories\&quot;, \&quot;positions\&quot;, \&quot;warning_types\&quot;, \&quot;leave_types\&quot;, \&quot;expense_types\&quot;]\r\n}&quot;,
  &quot;contentType&quot;: &quot;text/plain&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>1f798ed7-98b2-434e-afb7-b861128e18cb</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>Bearer ${alpha_token}</value>
      <webElementGuid>42e52403-12a7-479d-bb21-a53dc478cf83</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>${alpha_header_user_id_key}</name>
      <type>Main</type>
      <value>${alpha_header_user_id_value}</value>
      <webElementGuid>ee7c32dc-f358-4022-adc6-c755cc26113d</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Proxy-Authorization</name>
      <type>Main</type>
      <value>${SECRET_SERVICE}</value>
      <webElementGuid>21851c6f-1513-48b3-beb1-f26c624cb766</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>10.0.1</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <path></path>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>${alpha_gw_api_url}/company-settings</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.alpha_gw_api_url</defaultValue>
      <description></description>
      <id>e10be27a-af60-4c82-b791-fda91be7a088</id>
      <masked>false</masked>
      <name>alpha_gw_api_url</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.alpha_token</defaultValue>
      <description></description>
      <id>8e0da4e9-cc84-4934-a19c-2d752935c238</id>
      <masked>false</masked>
      <name>alpha_token</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.alpha_header_user_id_key</defaultValue>
      <description></description>
      <id>53cb1809-4ff2-4892-9ff8-3f8d4cd1227c</id>
      <masked>false</masked>
      <name>alpha_header_user_id_key</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.alpha_header_user_id_value</defaultValue>
      <description></description>
      <id>664aeccb-7dc1-40fb-ada9-9f68911551a4</id>
      <masked>false</masked>
      <name>alpha_header_user_id_value</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.SECRET_SERVICE</defaultValue>
      <description></description>
      <id>f1c20336-19f6-4f4d-a8df-39f6413745b4</id>
      <masked>false</masked>
      <name>SECRET_SERVICE</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
