<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>Update</name>
   <tag></tag>
   <elementGuidId>f0b4dcd6-3170-44e8-861c-54c21a1262b8</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\r\n    \&quot;company_logo\&quot; : \&quot;\&quot;,\r\n    \&quot;company_logo_doc_id\&quot; : \&quot;\&quot;,\r\n    \&quot;company_name\&quot; : \&quot;Apple 2\&quot;,\r\n    \&quot;company_hrd_email\&quot; : \&quot;hrd@apple.com\&quot;,\r\n    \&quot;account_holder_email\&quot; : \&quot;hrd@apple.com\&quot;,\r\n    \&quot;company_tax_id\&quot; : \&quot;\&quot;,\r\n    \&quot;company_address_1\&quot; : \&quot;Surabaya\&quot;,\r\n    \&quot;company_address_2\&quot; : \&quot;\&quot;,\r\n    \&quot;company_country\&quot; : \&quot;ID\&quot;,\r\n    \&quot;company_state\&quot; : \&quot;East Java\&quot;,\r\n    \&quot;company_city\&quot; : \&quot;Surabaya\&quot;,\r\n    \&quot;company_zip_code\&quot; : \&quot;61372\&quot;,\r\n    \&quot;company_default_locale\&quot; : \&quot;ID\&quot;,\r\n    \&quot;max_upload_filesize\&quot; : \&quot;2000\&quot;,\r\n    \&quot;status\&quot; : \&quot;0\&quot;,\r\n    \&quot;leave_setting_default_status\&quot; : \&quot;9\&quot;,\r\n    \&quot;leave_setting_annual_quota\&quot; : \&quot;ok\&quot;,\r\n    \&quot;expense_setting_default_status\&quot; : \&quot;9\&quot;,\r\n    \&quot;expense_setting_autocomplete\&quot; : \&quot;ok\&quot;,\r\n    \&quot;payroll_cutoff_date\&quot; : \&quot;24\&quot;,\r\n    \&quot;master_data\&quot; : [\r\n        \r\n    ]\r\n}&quot;,
  &quot;contentType&quot;: &quot;text/plain&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>3823e98f-5e04-4419-92e6-6884dde9fb4a</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>Bearer ${alpha_token}</value>
      <webElementGuid>9ec4a070-711c-44e9-a9df-845e6a4f615b</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>${alpha_header_user_id_key}</name>
      <type>Main</type>
      <value>${alpha_header_user_id_value}</value>
      <webElementGuid>bcbd6153-672b-41c0-8a79-b73ec8bba8e3</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Proxy-Authorization</name>
      <type>Main</type>
      <value>${SECRET_SERVICE}</value>
      <webElementGuid>7d1abd41-2dce-47da-ba32-f4178658718e</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>10.0.1</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <path></path>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>${alpha_gw_api_url}/company-settings/2/update</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.alpha_gw_api_url</defaultValue>
      <description></description>
      <id>25b7ddb2-455e-414e-8bfe-05948a0543cd</id>
      <masked>false</masked>
      <name>alpha_gw_api_url</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.alpha_token</defaultValue>
      <description></description>
      <id>a010ee5b-8e7f-4328-b8c3-d26bda95e955</id>
      <masked>false</masked>
      <name>alpha_token</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.alpha_header_user_id_key</defaultValue>
      <description></description>
      <id>4f978854-8b70-404a-9159-e18f0c55a3ff</id>
      <masked>false</masked>
      <name>alpha_header_user_id_key</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.alpha_header_user_id_value</defaultValue>
      <description></description>
      <id>0879bced-576b-47a6-afcf-953818af1943</id>
      <masked>false</masked>
      <name>alpha_header_user_id_value</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.SECRET_SERVICE</defaultValue>
      <description></description>
      <id>97fdf30c-d24c-41e9-98ee-c84dab9aa144</id>
      <masked>false</masked>
      <name>SECRET_SERVICE</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
