<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>Create</name>
   <tag></tag>
   <elementGuidId>d52ee4cc-baa1-4374-b6cf-cbf7d51b5e64</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\r\n    \&quot;name\&quot;: \&quot;Template 123x\&quot;,\r\n    \&quot;score_type_id\&quot;: 24,\r\n    \&quot;with_note\&quot;: 1,\r\n    \&quot;status\&quot; : 2,\r\n    \&quot;additional_questions\&quot;: {\r\n        \&quot;title\&quot; : \&quot;Ini custom\&quot;,\r\n        \&quot;description\&quot; : \&quot;Ini desc\&quot;,\r\n        \&quot;questions\&quot; : [\r\n            \&quot;custom pertanyaan 1\&quot;,\r\n            \&quot;custom pertanyaan 2\&quot;\r\n        ]\r\n    },\r\n    \&quot;template_details\&quot;: [\r\n        {\r\n            \&quot;type\&quot;: \&quot;category\&quot;,\r\n            \&quot;details\&quot;: [\r\n                {\r\n                    \&quot;title\&quot;: \&quot;Cat 1\&quot;,\r\n                    \&quot;description\&quot;: \&quot;Category 1 description\&quot;,\r\n                    \&quot;groups\&quot;: [\r\n                        {\r\n                            \&quot;type\&quot;: \&quot;group\&quot;,\r\n                            \&quot;title\&quot;: \&quot;Group 1\&quot;,\r\n                            \&quot;description\&quot;: \&quot;Group 1 description\&quot;,\r\n                            \&quot;questions\&quot;: [\r\n                                {\r\n                                    \&quot;type\&quot;: \&quot;question\&quot;,\r\n                                    \&quot;title\&quot;: \&quot;Question 1\&quot;,\r\n                                    \&quot;description\&quot;: \&quot;Description 1\&quot;,\r\n                                    \&quot;score_guidelines\&quot;: [\r\n                                        {\r\n                                            \&quot;score_value\&quot;: 10,\r\n                                            \&quot;description\&quot;: \&quot;dari sabang sampai merauke\&quot;\r\n                                        },\r\n                                        {\r\n                                            \&quot;score_value\&quot;: 20,\r\n                                            \&quot;description\&quot;: \&quot;dari sabang sampai merauke\&quot;\r\n                                        }\r\n                                    ]\r\n                                },\r\n                                {\r\n                                    \&quot;type\&quot;: \&quot;question\&quot;,\r\n                                    \&quot;title\&quot;: \&quot;Question 2\&quot;,\r\n                                    \&quot;description\&quot;: \&quot;Description 2\&quot;,\r\n                                    \&quot;score_guidelines\&quot;: []\r\n                                }\r\n                            ]\r\n                        }\r\n                    ]\r\n                }\r\n            ]\r\n        },\r\n        {\r\n            \&quot;type\&quot;: \&quot;group\&quot;,\r\n            \&quot;details\&quot;: [\r\n                {\r\n                    \&quot;title\&quot;: \&quot;Group 1\&quot;,\r\n                    \&quot;description\&quot;: \&quot;Group 1 description\&quot;,\r\n                    \&quot;questions\&quot;: [\r\n                        {\r\n                            \&quot;type\&quot;: \&quot;question\&quot;,\r\n                            \&quot;title\&quot;: \&quot;Question 1\&quot;,\r\n                            \&quot;description\&quot;: \&quot;Description 1\&quot;,\r\n                            \&quot;score_guidelines\&quot;: [\r\n                                {\r\n                                    \&quot;score_value\&quot;: 10,\r\n                                    \&quot;description\&quot;: \&quot;dari sabang sampai merauke\&quot;\r\n                                },\r\n                                {\r\n                                    \&quot;score_value\&quot;: 20,\r\n                                    \&quot;description\&quot;: \&quot;dari sabang sampai merauke\&quot;\r\n                                }\r\n                            ]\r\n                        },\r\n                        {\r\n                            \&quot;type\&quot;: \&quot;question\&quot;,\r\n                            \&quot;title\&quot;: \&quot;Question 2\&quot;,\r\n                            \&quot;description\&quot;: \&quot;Description 2\&quot;,\r\n                            \&quot;score_guidelines\&quot;: []\r\n                        }\r\n                    ]\r\n                },\r\n                {\r\n                    \&quot;title\&quot;: \&quot;G2\&quot;,\r\n                    \&quot;description\&quot;: \&quot;Group 2 description\&quot;,\r\n                    \&quot;questions\&quot;: []\r\n                }\r\n            ]\r\n        },\r\n        {\r\n            \&quot;type\&quot;: \&quot;question\&quot;,\r\n            \&quot;details\&quot;: [\r\n                {\r\n                    \&quot;title\&quot;: \&quot;question1\&quot;,\r\n                    \&quot;description\&quot;: \&quot;question 1\&quot;,\r\n                    \&quot;score_guidelines\&quot;: []\r\n                },\r\n                {\r\n                    \&quot;title\&quot;: \&quot;question2\&quot;,\r\n                    \&quot;description\&quot;: \&quot;question 2\&quot;,\r\n                    \&quot;score_guidelines\&quot;: []\r\n                }\r\n            ]\r\n        }\r\n    ]\r\n}&quot;,
  &quot;contentType&quot;: &quot;text/plain&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>ca18fae4-e141-4868-b938-fb59b4aebe8e</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>Bearer ${alpha_token}</value>
      <webElementGuid>6a5b2b36-61a5-4f4f-8cf1-2df92f564553</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>${alpha_header_user_id_key}</name>
      <type>Main</type>
      <value>${alpha_header_user_id_value}</value>
      <webElementGuid>338851ac-8735-4fdd-9d89-15a87c81cdb5</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Proxy-Authorization</name>
      <type>Main</type>
      <value>${SECRET_SERVICE}</value>
      <webElementGuid>31302c7c-fdbb-4997-b7f2-37ae3bbf545b</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>X-Company-Id</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e1d24288-ef78-49f5-9ccf-e7538beda86e</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>10.0.1</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <path></path>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>${alpha_gw_api_url}/templates</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.alpha_gw_api_url</defaultValue>
      <description></description>
      <id>69887d4b-ad01-445b-883a-0b9b91205c4f</id>
      <masked>false</masked>
      <name>alpha_gw_api_url</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.alpha_token</defaultValue>
      <description></description>
      <id>a43aad72-8b17-4541-b264-6d9e85fe8971</id>
      <masked>false</masked>
      <name>alpha_token</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.alpha_header_user_id_key</defaultValue>
      <description></description>
      <id>50b4e4ac-ccd9-493b-83fb-ec40622cfcbe</id>
      <masked>false</masked>
      <name>alpha_header_user_id_key</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.alpha_header_user_id_value</defaultValue>
      <description></description>
      <id>5462a3e5-7ad7-4f2e-85ec-97da32426f8e</id>
      <masked>false</masked>
      <name>alpha_header_user_id_value</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.SECRET_SERVICE</defaultValue>
      <description></description>
      <id>103ab87c-b3ba-4151-805e-48cec3767179</id>
      <masked>false</masked>
      <name>SECRET_SERVICE</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
