<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>Update</name>
   <tag></tag>
   <elementGuidId>a884de0e-e7b9-4f60-a30c-d348197cf1d7</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\r\n    \&quot;name\&quot;: \&quot;Update 1\&quot;,\r\n    \&quot;status\&quot; : 1,\r\n    \&quot;score_type_id\&quot;: 4,\r\n    \&quot;with_note\&quot;: 1,\r\n    \&quot;details\&quot;: [\r\n        {\r\n            \&quot;type\&quot;: \&quot;category\&quot;,\r\n            \&quot;title\&quot;: \&quot;Category 1\&quot;,\r\n            \&quot;description\&quot;: \&quot;Category 1 description\&quot;,\r\n            \&quot;groups\&quot;: [\r\n                {\r\n                    \&quot;type\&quot;: \&quot;group_question\&quot;,\r\n                    \&quot;title\&quot;: \&quot;Group 1\&quot;,\r\n                    \&quot;description\&quot;: \&quot;Group 1 description\&quot;,\r\n                    \&quot;parent_id\&quot;: null,\r\n                    \&quot;questions\&quot;: [\r\n                        {\r\n                            \&quot;type\&quot;: \&quot;question\&quot;,\r\n                            \&quot;title\&quot;: \&quot;Question 1\&quot;,\r\n                            \&quot;description\&quot;: \&quot;Description 1\&quot;,\r\n                            \&quot;score_guidelines\&quot; : [\r\n                                {\r\n                                    \&quot;score_value\&quot; : 10,\r\n                                    \&quot;description\&quot; : \&quot;dari sabang sampai merauke\&quot;\r\n                                },\r\n                                {\r\n                                    \&quot;score_value\&quot; : 20,\r\n                                    \&quot;description\&quot; : \&quot;dari sabang sampai merauke\&quot;\r\n                                }\r\n                            ] \r\n                        },\r\n                        {\r\n                            \&quot;type\&quot;: \&quot;question\&quot;,\r\n                            \&quot;title\&quot;: \&quot;Question 2\&quot;,\r\n                            \&quot;description\&quot;: \&quot;Description 2\&quot;\r\n                        }\r\n                    ]\r\n                }\r\n            ]\r\n        }\r\n    ]\r\n}\r\n&quot;,
  &quot;contentType&quot;: &quot;text/plain&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>a516a52d-93fd-4201-8b4c-e2c6b7dd0922</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>Bearer ${alpha_token}</value>
      <webElementGuid>6ac18920-5e83-44c6-b988-5eefe511079f</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>${alpha_header_user_id_key}</name>
      <type>Main</type>
      <value>${alpha_header_user_id_value}</value>
      <webElementGuid>feb6fc2d-2e44-414f-bbe3-6b0280eb3e08</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Proxy-Authorization</name>
      <type>Main</type>
      <value>${SECRET_SERVICE}</value>
      <webElementGuid>3ba6897b-f435-4a2c-9070-a82d00aa444a</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>X-Company-Id</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>678069d3-34a9-4adf-9086-cbb237510669</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>10.0.1</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <path></path>
   <restRequestMethod>PUT</restRequestMethod>
   <restUrl>${alpha_gw_api_url}/templates/23</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.alpha_gw_api_url</defaultValue>
      <description></description>
      <id>16b65f5c-9b2d-483c-8a9d-03d5f2d864b8</id>
      <masked>false</masked>
      <name>alpha_gw_api_url</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.alpha_token</defaultValue>
      <description></description>
      <id>e0c0bf5a-4baa-4fdb-9e23-73c7c20493fb</id>
      <masked>false</masked>
      <name>alpha_token</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.alpha_header_user_id_key</defaultValue>
      <description></description>
      <id>c62295f2-f2ec-461f-bd5e-a28d0816ab05</id>
      <masked>false</masked>
      <name>alpha_header_user_id_key</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.alpha_header_user_id_value</defaultValue>
      <description></description>
      <id>c6b3ec3e-aee9-48cb-9597-d566062e8c5f</id>
      <masked>false</masked>
      <name>alpha_header_user_id_value</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.SECRET_SERVICE</defaultValue>
      <description></description>
      <id>80e4e9da-7b3d-4cad-b8db-c6f6a4ffa904</id>
      <masked>false</masked>
      <name>SECRET_SERVICE</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
