<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>Update</name>
   <tag></tag>
   <elementGuidId>54713c5e-d1b6-4237-a1e8-68a913d549a8</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\n    \&quot;name\&quot;: \&quot;SenioraStaffA\&quot;,\n    \&quot;code\&quot;: \&quot;SSS\&quot;,\n    \&quot;description\&quot;: \&quot;Senior Staff\&quot;,\n    \&quot;is_manager\&quot; : 1,\n    \&quot;reviewer\&quot; : [\n        {\n            \&quot;name\&quot; : null,\n            \&quot;department_id\&quot; : 1,\n            \&quot;category_id\&quot; : 1,\n            \&quot;role_id\&quot; : 4,\n            \&quot;order\&quot; : 1\n        },\n        {\n            \&quot;name\&quot; : null,\n            \&quot;department_id\&quot; : 2,\n            \&quot;category_id\&quot; : 2,\n            \&quot;role_id\&quot; : 4,\n            \&quot;order\&quot; : 2\n        },\n        {\n            \&quot;name\&quot; : null,\n            \&quot;department_id\&quot; : 2,\n            \&quot;category_id\&quot; : 1,\n            \&quot;role_id\&quot; : 4,\n            \&quot;order\&quot; : 3\n        }\n    ]\n}&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>54a68085-16e1-4625-87b5-c93ee2f48eb5</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>267eb8a3-48c1-4db1-bce2-04dc871c0232</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>10.0.1</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <path></path>
   <restRequestMethod>PUT</restRequestMethod>
   <restUrl>${alpha_gw_api_url}/categories/1</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.alpha_gw_api_url</defaultValue>
      <description></description>
      <id>5912c433-bb0a-434f-922f-6ee82aa7931d</id>
      <masked>false</masked>
      <name>alpha_gw_api_url</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
