<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>update</name>
   <tag></tag>
   <elementGuidId>0d0cbe18-b29b-4032-b544-8ce37077d413</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\r\n    \&quot;name\&quot;: \&quot;Cycle : monthly, join_date, before 2 week, 1 times with new settings\&quot;,\r\n    \&quot;status\&quot;: 7,\r\n    \&quot;timeframe_id\&quot;: 1,\r\n    \&quot;custom_duration\&quot;: null,\r\n    \&quot;custom_period\&quot;: null,\r\n    \&quot;cycle_period\&quot;: 1,\r\n    \&quot;timeframe_date\&quot;: \&quot;join_date\&quot;,\r\n    \&quot;timeframe_duration\&quot;: null,\r\n    \&quot;timeframe_period\&quot;: null,\r\n    \&quot;timeframe_spesific_date\&quot;: null,\r\n    \&quot;generate_option\&quot;: 0,\r\n    \&quot;review_duration\&quot;: 2,\r\n    \&quot;review_period\&quot;: 2,\r\n    \&quot;cycle_targets\&quot;: [\r\n        {\r\n            \&quot;review_target\&quot;: \&quot;filtered_employee\&quot;,\r\n            \&quot;detail_value\&quot;: [\r\n                {\r\n                    \&quot;department_id\&quot;: [\r\n                        1,\r\n                        2\r\n                    ],\r\n                    \&quot;department_category_id\&quot;: [\r\n                        3,\r\n                        4\r\n                    ]\r\n                },\r\n                {\r\n                    \&quot;department_id\&quot;: [\r\n                        1\r\n                    ],\r\n                    \&quot;department_category_id\&quot;: [\r\n                        1\r\n                    ],\r\n                    \&quot;employment_period_id\&quot;: [\r\n                        2\r\n                    ],\r\n                    \&quot;position_id\&quot;: [\r\n                        3\r\n                    ]\r\n                }\r\n            ]\r\n        }\r\n    ],\r\n    \&quot;cycle_details\&quot;: [\r\n        {\r\n            \&quot;review_method_id\&quot;: 1, // Untuk manager review\r\n            \&quot;template_id\&quot;: 5,\r\n            \&quot;set_weight\&quot;: 50\r\n        },\r\n        {\r\n            \&quot;review_method_id\&quot;: 2, // Untuk peer review\r\n            \&quot;template_id\&quot;: 5,\r\n            \&quot;set_weight\&quot;: 5\r\n        },\r\n        {\r\n            \&quot;review_method_id\&quot;: 3, // Untuk self review\r\n            \&quot;template_id\&quot;: 5,\r\n            \&quot;set_weight\&quot;: 5\r\n        }\r\n    ],\r\n    \&quot;settings\&quot;: {\r\n        \&quot;quality\&quot;: {\r\n            \&quot;template_id\&quot;: 1,\r\n            \&quot;set_weight\&quot;: 5\r\n        },\r\n        \&quot;overall\&quot;: {\r\n            \&quot;set_weight\&quot;: 5,\r\n            \&quot;overall_detail\&quot;: [\r\n                {\r\n                    \&quot;Question\&quot;: \&quot;Question A\&quot;,\r\n                    \&quot;Score\&quot;: 20\r\n                },\r\n                {\r\n                    \&quot;Question\&quot;: \&quot;Question B\&quot;,\r\n                    \&quot;Score\&quot;: 30\r\n                }\r\n            ]\r\n        },\r\n        \&quot;indisciplinary\&quot;: {\r\n            \&quot;set_weight\&quot;: 5,\r\n            \&quot;detail\&quot;: [\r\n                {\r\n                    // Misal sick\r\n                    \&quot;type\&quot;: 1,\r\n                    \&quot;from\&quot;: \&quot;Alpha\&quot;,\r\n                    \&quot;set_weight\&quot;: 10\r\n                },\r\n                {\r\n                    \&quot;type\&quot;: 2,\r\n                    \&quot;from\&quot;: \&quot;Alpha\&quot;,\r\n                    \&quot;set_weight\&quot;: 20\r\n                },\r\n                {\r\n                    \&quot;type\&quot;: 3,\r\n                    \&quot;from\&quot;: \&quot;Manual\&quot;,\r\n                    \&quot;set_weight\&quot;: 70\r\n                }\r\n            ]\r\n        },\r\n        \&quot;certification\&quot;: 1,\r\n        \&quot;recommendations\&quot;: [\r\n            1,\r\n            2,\r\n            3\r\n        ],\r\n        \&quot;additional_notes\&quot;: 1\r\n    }\r\n}&quot;,
  &quot;contentType&quot;: &quot;text/plain&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>bc4e7042-261c-45b1-afdc-c7692f860c3c</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>Bearer ${alpha_token}</value>
      <webElementGuid>5c069c87-41c9-4ce1-8512-9625eec21007</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>${alpha_header_user_id_key}</name>
      <type>Main</type>
      <value>${alpha_header_user_id_value}</value>
      <webElementGuid>99de9ab6-8b15-48cb-9e0c-6f4100a308a7</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Proxy-Authorization</name>
      <type>Main</type>
      <value>${SECRET_SERVICE}</value>
      <webElementGuid>f3672f05-f177-4b7e-83a6-acbad2c4a72f</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>X-Company-Id</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f02603fc-75b4-4a74-a4ff-aeba41dca851</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>10.0.1</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <path></path>
   <restRequestMethod>PUT</restRequestMethod>
   <restUrl>${alpha_gw_api_url}/cycles/1</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.alpha_gw_api_url</defaultValue>
      <description></description>
      <id>ebe93677-51c2-4d96-8b6e-5ba0572d4d8f</id>
      <masked>false</masked>
      <name>alpha_gw_api_url</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.alpha_token</defaultValue>
      <description></description>
      <id>c301aaf9-35dd-4d1f-84c0-1931131e4dd6</id>
      <masked>false</masked>
      <name>alpha_token</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.alpha_header_user_id_key</defaultValue>
      <description></description>
      <id>341b82b7-4f61-401c-965a-0db5ece07963</id>
      <masked>false</masked>
      <name>alpha_header_user_id_key</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.alpha_header_user_id_value</defaultValue>
      <description></description>
      <id>517183a8-fe5b-4376-95a7-07537b341a23</id>
      <masked>false</masked>
      <name>alpha_header_user_id_value</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.SECRET_SERVICE</defaultValue>
      <description></description>
      <id>ab78007c-75a2-4e61-ad47-49b9c9c3d738</id>
      <masked>false</masked>
      <name>SECRET_SERVICE</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
