<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>Delete File (ok)</name>
   <tag></tag>
   <elementGuidId>76d2fe61-29b3-4238-b10a-2635a1193c99</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent></httpBodyContent>
   <httpBodyType></httpBodyType>
   <katalonVersion>10.0.1</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <path></path>
   <restRequestMethod>DELETE</restRequestMethod>
   <restUrl>${alpha_gw_api_url}/finance-docs/${finance_doc_id}/employee/${employee_id}</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.alpha_gw_api_url</defaultValue>
      <description></description>
      <id>7a3b9417-e045-452c-8fad-5ee9a446bafb</id>
      <masked>false</masked>
      <name>alpha_gw_api_url</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.finance_doc_id</defaultValue>
      <description></description>
      <id>ee68c5ea-3d1c-4736-80fe-c5a7454f8e19</id>
      <masked>false</masked>
      <name>finance_doc_id</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.employee_id</defaultValue>
      <description></description>
      <id>b1ca8338-d427-4c98-94b5-18945be0b6f7</id>
      <masked>false</masked>
      <name>employee_id</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
