<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>Revision</name>
   <tag></tag>
   <elementGuidId>aebd2077-019e-4a82-a70a-b62ca2fdfc64</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\r\n    \&quot;allowance\&quot; : [\r\n        {\r\n            \&quot;type_id\&quot;: 1,\r\n            \&quot;currency\&quot;: \&quot;idr\&quot;,\r\n            \&quot;value\&quot;: 1000\r\n        },\r\n        {\r\n            \&quot;type_id\&quot;: 2,\r\n            \&quot;currency\&quot;: \&quot;idr\&quot;,\r\n            \&quot;value\&quot;: 200000\r\n        }\r\n    ],\r\n    \&quot;deduction\&quot; : [\r\n        {\r\n            \&quot;type_id\&quot;: 1,\r\n            \&quot;currency\&quot;: \&quot;idr\&quot;,\r\n            \&quot;value\&quot;: 1000000\r\n        },\r\n        {\r\n            \&quot;type_id\&quot;: 2,\r\n            \&quot;currency\&quot;: \&quot;idr\&quot;,\r\n            \&quot;value\&quot;: 2000000\r\n        }\r\n    ],\r\n    \&quot;tax\&quot; : [\r\n        {\r\n            \&quot;type_id\&quot;: 1,\r\n            \&quot;currency\&quot;: \&quot;idr\&quot;,\r\n            \&quot;value\&quot;: 500000\r\n        },\r\n        {\r\n            \&quot;type_id\&quot;: 2,\r\n            \&quot;currency\&quot;: \&quot;idr\&quot;,\r\n            \&quot;value\&quot;: 1234567\r\n        }\r\n    ],\r\n    \&quot;payslip_bank_account\&quot;:\r\n        {\r\n            \&quot;id\&quot;: 1,\r\n            \&quot;employee_uuid\&quot;: \&quot;f3581194-77d9-434e-85c9-e2ed8c7757d3\&quot;,\r\n            \&quot;bank_name\&quot;: \&quot;BCA\&quot;,\r\n            \&quot;branch_name\&quot;: \&quot;DIPONEGORO\&quot;,\r\n            \&quot;account_no\&quot;: \&quot;1234567890\&quot;,\r\n            \&quot;account_name\&quot;: \&quot;John Doe\&quot;,\r\n            \&quot;city\&quot;: \&quot;South Jakarta\&quot;,\r\n            \&quot;country\&quot;: \&quot;ID\&quot;,\r\n            \&quot;swiftcode\&quot;: \&quot;iqwye6\&quot;,\r\n            \&quot;currency\&quot;: \&quot;idr\&quot;,\r\n            \&quot;created_at\&quot;: \&quot;2020-09-04 01:14:17\&quot;,\r\n            \&quot;created_by\&quot;: \&quot;System: 1234567899\&quot;,\r\n            \&quot;updated_at\&quot;: \&quot;2020-09-04 01:14:17\&quot;,\r\n            \&quot;updated_by\&quot;: \&quot;System: 1234567899\&quot;\r\n        }\r\n    \r\n}&quot;,
  &quot;contentType&quot;: &quot;text/plain&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>f0f6ca56-9cfe-4b98-8c79-c69f4d61ade7</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>Bearer ${alpha_token}</value>
      <webElementGuid>1e0951a1-8afc-44a1-a48f-cb8f38bc8104</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>${alpha_header_user_id_key}</name>
      <type>Main</type>
      <value>${alpha_header_user_id_value}</value>
      <webElementGuid>faca10d9-354d-4d78-b524-4ace2ac934b9</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Proxy-Authorization</name>
      <type>Main</type>
      <value>${SECRET_SERVICE}</value>
      <webElementGuid>100fba78-1c6d-466d-8a59-acad7f974eb3</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>10.0.1</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <path></path>
   <restRequestMethod>PUT</restRequestMethod>
   <restUrl>${alpha_gw_api_url}/payslip/${payslip_id}/revision</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.alpha_gw_api_url</defaultValue>
      <description></description>
      <id>194fc285-807a-42f7-9317-2fc2d7208b8c</id>
      <masked>false</masked>
      <name>alpha_gw_api_url</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.payslip_id</defaultValue>
      <description></description>
      <id>b004199c-461d-4411-b5c5-f5ca77b46c59</id>
      <masked>false</masked>
      <name>payslip_id</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.alpha_token</defaultValue>
      <description></description>
      <id>70298fa9-4002-43ee-b6ac-f1b481f9d59c</id>
      <masked>false</masked>
      <name>alpha_token</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.alpha_header_user_id_key</defaultValue>
      <description></description>
      <id>2c594f49-a2cf-4998-bcdd-6a595641439d</id>
      <masked>false</masked>
      <name>alpha_header_user_id_key</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.alpha_header_user_id_value</defaultValue>
      <description></description>
      <id>6dd9a7f8-df59-4401-9fc5-4927119cd156</id>
      <masked>false</masked>
      <name>alpha_header_user_id_value</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.SECRET_SERVICE</defaultValue>
      <description></description>
      <id>370fc920-6b03-4f95-b62d-50cb80bee264</id>
      <masked>false</masked>
      <name>SECRET_SERVICE</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
