<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>Update publish</name>
   <tag></tag>
   <elementGuidId>d1d3b8c2-21ca-4d91-be39-c6136f433591</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\r\n    \&quot;allowance\&quot; : [\r\n        {\r\n            \&quot;type_id\&quot;: 1,\r\n            \&quot;currency\&quot;: \&quot;idr\&quot;,\r\n            \&quot;value\&quot;: 50000\r\n        },\r\n        {\r\n            \&quot;type_id\&quot;: 2,\r\n            \&quot;currency\&quot;: \&quot;idr\&quot;,\r\n            \&quot;value\&quot;: 150000\r\n        }\r\n    ],\r\n    \&quot;deduction\&quot; : [\r\n        {\r\n            \&quot;type_id\&quot;: 1,\r\n            \&quot;currency\&quot;: \&quot;idr\&quot;,\r\n            \&quot;value\&quot;: 50000\r\n        },\r\n        {\r\n            \&quot;type_id\&quot;: 2,\r\n            \&quot;currency\&quot;: \&quot;idr\&quot;,\r\n            \&quot;value\&quot;: 50000\r\n        }\r\n    ],\r\n    \&quot;tax\&quot; : [\r\n        {\r\n            \&quot;type_id\&quot;: 1,\r\n            \&quot;currency\&quot;: \&quot;idr\&quot;,\r\n            \&quot;value\&quot;: 40000\r\n        },\r\n        {\r\n            \&quot;type_id\&quot;: 2,\r\n            \&quot;currency\&quot;: \&quot;idr\&quot;,\r\n            \&quot;value\&quot;: 60000\r\n        }\r\n    ],\r\n    \&quot;payslip_bank_account\&quot;:\r\n        {\r\n            \&quot;id\&quot;: 1,\r\n            \&quot;employee_uuid\&quot;: \&quot;f3581194-77d9-434e-85c9-e2ed8c7757d3\&quot;,\r\n            \&quot;bank_name\&quot;: \&quot;BCA\&quot;,\r\n            \&quot;branch_name\&quot;: \&quot;DIPONEGORO\&quot;,\r\n            \&quot;account_no\&quot;: \&quot;1234567890\&quot;,\r\n            \&quot;account_name\&quot;: \&quot;John Doe\&quot;,\r\n            \&quot;city\&quot;: \&quot;South Jakarta\&quot;,\r\n            \&quot;country\&quot;: \&quot;ID\&quot;,\r\n            \&quot;swiftcode\&quot;: \&quot;iqwye6\&quot;,\r\n            \&quot;currency\&quot;: \&quot;idr\&quot;,\r\n            \&quot;created_at\&quot;: \&quot;2020-09-04 01:14:17\&quot;,\r\n            \&quot;created_by\&quot;: \&quot;System: 1234567899\&quot;,\r\n            \&quot;updated_at\&quot;: \&quot;2020-09-04 01:14:17\&quot;,\r\n            \&quot;updated_by\&quot;: \&quot;System: 1234567899\&quot;\r\n        }\r\n    \r\n}&quot;,
  &quot;contentType&quot;: &quot;text/plain&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>73d0cc95-1339-424d-8d6d-d2d1f896e4d7</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>Bearer ${alpha_token}</value>
      <webElementGuid>f2ec460a-2222-4f75-9133-c830d6788d31</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>${alpha_header_user_id_key}</name>
      <type>Main</type>
      <value>${alpha_header_user_id_value}</value>
      <webElementGuid>c4ce9bc9-5d86-4ab2-9ac3-8a20bfd776af</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Proxy-Authorization</name>
      <type>Main</type>
      <value>${SECRET_SERVICE}</value>
      <webElementGuid>bca961e9-df39-4d1d-b0b9-5191b7e43e55</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>10.0.1</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <path></path>
   <restRequestMethod>PUT</restRequestMethod>
   <restUrl>${alpha_gw_api_url}/payslip/${payslip_id}/update-publsih</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.alpha_gw_api_url</defaultValue>
      <description></description>
      <id>040c0ccc-1e64-4cf9-8f1a-ad1a4af61c35</id>
      <masked>false</masked>
      <name>alpha_gw_api_url</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.payslip_id</defaultValue>
      <description></description>
      <id>e2800e72-829d-4c95-acfa-5c2e62085d74</id>
      <masked>false</masked>
      <name>payslip_id</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.alpha_token</defaultValue>
      <description></description>
      <id>92a9de45-dc47-40f5-93b2-603cabf76cf3</id>
      <masked>false</masked>
      <name>alpha_token</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.alpha_header_user_id_key</defaultValue>
      <description></description>
      <id>6e0284f2-68e9-4e75-952e-30570d64ae53</id>
      <masked>false</masked>
      <name>alpha_header_user_id_key</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.alpha_header_user_id_value</defaultValue>
      <description></description>
      <id>52f78ff4-393a-40a5-9f3d-3e1e4735d94b</id>
      <masked>false</masked>
      <name>alpha_header_user_id_value</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.SECRET_SERVICE</defaultValue>
      <description></description>
      <id>291c114a-dc1b-4d30-8674-062cb1848d2e</id>
      <masked>false</masked>
      <name>SECRET_SERVICE</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
